x-common-deploy: &common-deploy
  restart_policy:
    condition: on-failure
    delay: 5s
    window: 120s
x-common-env: &common-env
  PLEX_GID: 1000
  PLEX_UID: 1000
  TZ: Europe/Paris

networks:
  backend: {}
  public:
    external: true

services:
  plex:
    # Linux capabilities configuration:
    # We start by dropping ALL capabilities to improve container security.
    # Then we add back only the minimal set required for Plex to function properly.
    # These capabilities allow Plex to:
    # - access and manage files (CHOWN, DAC_OVERRIDE, FOWNER)
    # - run as a non-root user (SETUID, SETGID)
    # - open required network ports (NET_BIND_SERVICE)
    # - manage internal processes (KILL)
    # - write audit logs (AUDIT_WRITE)
    # - support certain transcoding/debug operations (SYS_PTRACE)
    # Removing any of these may cause Plex to fail to start or operate correctly.
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETUID
      - SETGID
      - NET_BIND_SERVICE
      - KILL
      - AUDIT_WRITE
      - SYS_PTRACE
    cap_drop:
      - ALL
    deploy:
      !!merge <<: *common-deploy
      labels:
        # Autoheal 
        - "autoheal=true"
        # Traefik configuration
        - "traefik.enable=true"
        - "traefik.http.routers.plex.rule=Host(`plex.$DOMAIN_NAME`)"
        - "traefik.http.routers.plex.entrypoints=https"
        - "traefik.http.services.plex.loadbalancer.server.port=32400"
        # Homepage configuration
        - "homepage.description=Stream your movies, TV shows, music, and photos to any device, providing a centralized media hub for all your content."
        - "homepage.group=Media Streaming"
        - "homepage.href=https://plex.$DOMAIN_NAME"
        - "homepage.icon=plex.png"
        - "homepage.name=Plex Media Server"
        - "homepage.weight=4"
        - "homepage.widget.key=$PLEX_TOKEN"
        - "homepage.widget.type=plex"
        - "homepage.widget.url=http://plex:32400"
    environment:
      !!merge <<: *common-env
      HOSTNAME: "MediaHost"
    image: plexinc/pms-docker:1.42.2.10156-f737b826c
    networks:
      - public
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    security_opt:
      - no-new-privileges:true
    volumes:
      - $STORAGE_PATH/media/plex:/config
      - $MEDIA_PATH:/mnt/media