x-common-deploy: &common-deploy
  restart_policy:
    condition: on-failure
    delay: 5s
    window: 120s
x-common-env: &common-env
  PGID: 1000
  PUID: 1000
  TZ: Europe/Paris

networks:
  backend: {}
  public:
    external: true

services:
  sonarr:
    cap_add:
      - SETUID
      - SETGID
    cap_drop:
      - "ALL"
    deploy:
      !!merge <<: *common-deploy
      labels:
        # Traefik configuration
        - "traefik.enable=true"
        - "traefik.http.routers.sonarr.rule=Host(`sonarr.$DOMAIN_NAME`)"
        - "traefik.http.routers.sonarr.entrypoints=https"
        - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
        - "traefik.http.routers.sonarr.middlewares=auth-manager"
        # Homepage configuration
        - "homepage.group=TV Management"
        - "homepage.name=Sonarr TV"
        - "homepage.icon=sonarr.png"
        - "homepage.href=https://sonarr.$DOMAIN_NAME"
        - "homepage.description=Manages your TV show downloads, automatically finding and adding new episodes as they air, keeping your library organized."
        - "homepage.weight=0"
        - "homepage.widget.type=sonarr"
        - "homepage.widget.url=http://sonarr:8989"
        - "homepage.widget.key=$SONARR_API_KEY"
      resources:
        limits:
          cpus: '1.0'
          memory: 2048M
        reservations:
          cpus: '0.5'
          memory: 512M
    environment:
      !!merge <<: *common-env
    image: lscr.io/linuxserver/sonarr:4.0.16
    networks:
      - public
    security_opt:
      - no-new-privileges:true
    volumes:
      - $STORAGE_PATH/media/sonarr:/config
      - $MEDIA_PATH:/mnt/media